import type { Channel, ChannelCategory } from '@/lib/types';

export const channels: Channel[] = [
  {
    id: 'cbs-news',
    name: 'CBS News',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/102/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/101/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'https://cbsn-us.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8',
    type: 'hls',
  },
  {
    id: 'nick-bangla',
    name: 'NICK BANGLA',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/202/100/100',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/201/600/400',
    thumbnailImageHint: 'cartoon animation',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_1341.m3u8',
    type: 'hls',
  },
  {
    id: 'sony',
    name: 'SONY',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/302/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/301/600/400',
    thumbnailImageHint: 'red carpet',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_551.m3u8',
    type: 'hls',
  },
  {
    id: 'cartoon-network',
    name: 'Cartoon Network',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/402/100/100',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/401/600/400',
    thumbnailImageHint: 'cartoon characters',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_816.m3u8',
    type: 'hls',
  },
  {
    id: 'zb-cartoon',
    name: 'ZB Cartoon',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/502/100/100',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/501/600/400',
    thumbnailImageHint: 'cartoon fun',
    streamUrl: 'https://server.zillarbarta.com/zbcatun/video.m3u8',
    type: 'hls',
  },
  {
    id: 'discovery-bengali',
    name: 'DISCOVERY CHANNEL BENGALI',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/602/100/100',
    logoImageHint: 'discovery logo',
    thumbnailUrl: 'https://picsum.photos/seed/601/600/400',
    thumbnailImageHint: 'nature documentary',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_573.m3u8',
    type: 'hls',
  },
  {
    id: 'colors-bengali-hd',
    name: 'COLORS BENGALI HD',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/702/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/701/600/400',
    thumbnailImageHint: 'drama series',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_756.m3u8',
    type: 'hls',
  },
  {
    id: 'sonic-bangla',
    name: 'SONIC BANGLA',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/802/100/100',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/801/600/400',
    thumbnailImageHint: 'action cartoon',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_1345.m3u8',
    type: 'hls',
  },
  {
    id: 'tv9-bangla',
    name: 'TV9 BANGLA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/902/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/901/600/400',
    thumbnailImageHint: 'news report',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_1735.m3u8',
    type: 'hls',
  },
  {
    id: 'r-bangla',
    name: 'R BANGLA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/1002/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/1001/600/400',
    thumbnailImageHint: 'breaking news',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_2780.m3u8',
    type: 'hls',
  },
  {
    id: 'rupashi-bangla',
    name: 'RUPASHI BANGLA',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/1102/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/1101/600/400',
    thumbnailImageHint: 'drama series',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_3005.m3u8',
    type: 'hls',
  },
  {
    id: 'abp-ananda',
    name: 'ABP ANANDA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/1202/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/1201/600/400',
    thumbnailImageHint: 'live news',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_672.m3u8',
    type: 'hls',
  },
  {
    id: 'sangeet-bangla',
    name: 'SANGEET BANGLA',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1302/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1301/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_740.m3u8',
    type: 'hls',
  },
  {
    id: 'b4u-music',
    name: 'B4U Music',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1402/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1401/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'https://cdnb4u.wiseplayout.com/B4U_Music/master.m3u8',
    type: 'hls',
  },
  {
    id: '9xm',
    name: '9XM',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1502/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1501/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'https://9xjio.wiseplayout.com/9XM/master.m3u8',
    type: 'hls',
  },
  {
    id: '9x-jalwa',
    name: '9X Jalwa',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1602/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1601/600/400',
    thumbnailImageHint: 'bollywood music',
    streamUrl: 'https://9xjio.wiseplayout.com/9XJALWA/master.m3u8',
    type: 'hls',
  },
  {
    id: 'colors-bangla-cinema',
    name: 'COLORS BANGLA CINEMA',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/1702/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/1701/600/400',
    thumbnailImageHint: 'movie scene',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_1657.m3u8',
    type: 'hls',
  },
  {
    id: 'zee-24-ghanta',
    name: 'ZEE 24 GHANTA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/1802/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/1801/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_464.m3u8',
    type: 'hls',
  },
  {
    id: 'sony-aath',
    name: 'SONY AATH',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/1902/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/1901/600/400',
    thumbnailImageHint: 'drama series',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_697.m3u8',
    type: 'hls',
  },
  {
    id: 'rongeen-tv',
    name: 'RONGEEN TV',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/2002/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/2001/600/400',
    thumbnailImageHint: 'colorful pattern',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_1667.m3u8',
    type: 'hls',
  },
  {
    id: 'colors-hd',
    name: 'COLORS HD',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/2102/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/2101/600/400',
    thumbnailImageHint: 'reality show',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_144.m3u8',
    type: 'hls',
  },
  {
    id: 'aaj-tak',
    name: 'AAJ TAK',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/2202/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/2201/600/400',
    thumbnailImageHint: 'news headline',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_173.m3u8',
    type: 'hls',
  },
  {
    id: 'dd-national-hd',
    name: 'DD NATIONAL HD',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/2302/100/100',
    logoImageHint: 'tv logo',
    thumbnailUrl: 'https://picsum.photos/seed/2301/600/400',
    thumbnailImageHint: 'classic show',
    streamUrl: 'https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8',
    type: 'hls',
  },
  {
    id: 'dd-india',
    name: 'DD India',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/2402/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/2401/600/400',
    thumbnailImageHint: 'international news',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_202.m3u8',
    type: 'hls',
  },
  {
    id: 'music-india',
    name: 'MUSIC INDIA',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/2502/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/2501/600/400',
    thumbnailImageHint: 'indian music',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_250.m3u8',
    type: 'hls',
  },
  {
    id: 'mtv',
    name: 'MTV',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/2602/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/2601/600/400',
    thumbnailImageHint: 'pop music',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_248.m3u8',
    type: 'hls',
  },
  {
    id: 'colors-cineplex-hd',
    name: 'COLORS CINEPLEX HD',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/2702/100/100',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/2701/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_1477.m3u8',
    type: 'hls',
  },
  {
    id: 'animal-planet',
    name: 'ANIMAL PLANET',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/2802/100/100',
    logoImageHint: 'animal logo',
    thumbnailUrl: 'https://picsum.photos/seed/2801/600/400',
    thumbnailImageHint: 'wildlife',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_566.m3u8',
    type: 'hls',
  },
  {
    id: 'history-tv-18',
    name: 'HISTORY TV 18',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/2902/100/100',
    logoImageHint: 'history logo',
    thumbnailUrl: 'https://picsum.photos/seed/2901/600/400',
    thumbnailImageHint: 'historical document',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_578.m3u8',
    type: 'hls',
  },
  {
    id: 'dd-kisan',
    name: 'DD KISAN',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/3002/100/100',
    logoImageHint: 'farming logo',
    thumbnailUrl: 'https://picsum.photos/seed/3001/600/400',
    thumbnailImageHint: 'agriculture field',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_583.m3u8',
    type: 'hls',
  },
  {
    id: 'sun-neo',
    name: 'SUN NEO',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/3102/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/3101/600/400',
    thumbnailImageHint: 'tv show',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_3088.m3u8',
    type: 'hls',
  },
  {
    id: 'dangal',
    name: 'DANGAL',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/3202/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/3201/600/400',
    thumbnailImageHint: 'indian drama',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_701.m3u8',
    type: 'hls',
  },
  {
    id: 'b4u-kadak',
    name: 'B4U KADAK',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/3302/100/100',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/3301/600/400',
    thumbnailImageHint: 'action movie',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_978.m3u8',
    type: 'hls',
  },
  {
    id: 'dd-sports',
    name: 'DD SPORTS',
    category: 'Sports',
    logoUrl: 'https://picsum.photos/seed/3402/100/100',
    logoImageHint: 'sports logo',
    thumbnailUrl: 'https://picsum.photos/seed/3401/600/400',
    thumbnailImageHint: 'cricket match',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_204.m3u8',
    type: 'hls',
  },
  {
    id: 'wion',
    name: 'WION',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/3502/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/3501/600/400',
    thumbnailImageHint: 'world news',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_412.m3u8',
    type: 'hls',
  },
  {
    id: 'pogo',
    name: 'POGO',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/3602/100/100',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/3601/600/400',
    thumbnailImageHint: 'kids cartoon',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_559.m3u8',
    type: 'hls',
  },
  {
    id: 'star-jalsha',
    name: 'Star Jalsha',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/3702/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/3701/600/400',
    thumbnailImageHint: 'bengali drama',
    streamUrl: 'https://allinonereborn.xyz/amit/host.php?id=54161',
    type: 'hls',
  },
  {
    id: 'jalsha-movies-hd',
    name: 'Jalsha Movies HD',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/3802/100/100',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/3801/600/400',
    thumbnailImageHint: 'movie poster',
    streamUrl: 'https://cdn.stmify.com/embed-free/v1/jalsha-movies-hd-in-jw',
    type: 'iframe',
  },
  {
    id: 'willow-hd',
    name: 'Willow HD',
    category: 'Sports',
    logoUrl: 'https://picsum.photos/seed/3902/100/100',
    logoImageHint: 'sports logo',
    thumbnailUrl: 'https://picsum.photos/seed/3901/600/400',
    thumbnailImageHint: 'cricket sport',
    streamUrl: 'https://sports.dtvworld.site/prime?id=willow',
    type: 'iframe',
  },
  {
    id: 'goldmines',
    name: 'GOLDMINES',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/4002/100/100',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/4001/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'https://cdn-2.pishow.tv/live/1459/master.m3u8',
    type: 'hls',
  },
  {
    id: 'gopal-bhar',
    name: 'GOPAL BHAR',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/4102/100/100',
    logoImageHint: 'cartoon character',
    thumbnailUrl: 'https://picsum.photos/seed/4101/600/400',
    thumbnailImageHint: 'cartoon character',
    streamUrl: 'https://live20.bozztv.com/giatvplayout7/giatv-209611/index.m3u8',
    type: 'hls',
  },
  {
    id: 'green-gold-tv',
    name: 'Green Gold Tv',
    category: 'Kids',
    logoUrl: 'https://images.unsplash.com/photo-1512529920731-e8abaea917a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxraWRzJTIwbG9nb3xlbnwwfHx8fDE3Njg5MjE0NDN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://images.unsplash.com/photo-1758789887939-dea05e990b48?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxjYXJ0b29uJTIwc2hvd3xlbnwwfHx8fDE3Njg5MjE0NDN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    thumbnailImageHint: 'cartoon show',
    streamUrl: 'https://vglivessai.akamaized.net/ptnr-yupptv/title-Green_Gold_India/eu/v1/manifest/611d79b11b77e2f571934fd80ca1413453772ac7/675a37e5-f517-434e-adae-d25ae1706340/48c68bfd-7883-4b85-9d1b-1548b66174a5/1.m3u8',
    type: 'hls',
  },
  {
    id: 'mastiii',
    name: 'Mastiii',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/4302/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/4301/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'https://d1msejlow1t3l4.cloudfront.net/211125/mastii/chunks.m3u8',
    type: 'hls',
  },
];

export const categories: { name: ChannelCategory; slug: string; imageUrl: string; imageHint: string; }[] = [
  { name: 'News', slug: 'news', imageUrl: 'https://picsum.photos/seed/cat-news/600/400', imageHint: 'news broadcast' },
  { name: 'Kids', slug: 'kids', imageUrl: 'https://picsum.photos/seed/cat-kids/600/400', imageHint: 'cartoon characters' },
  { name: 'Entertainment', slug: 'entertainment', imageUrl: 'https://picsum.photos/seed/cat-ent/600/400', imageHint: 'movie set' },
  { name: 'Movies', slug: 'movies', imageUrl: 'https://picsum.photos/seed/cat-movies/600/400', imageHint: 'film reel' },
  { name: 'Music', slug: 'music', imageUrl: 'https://picsum.photos/seed/cat-music/600/400', imageHint: 'live concert' },
  { name: 'Sports', slug: 'sports', imageUrl: 'https://picsum.photos/seed/cat-sports/600/400', imageHint: 'stadium lights' },
  { name: 'Infotainment', slug: 'infotainment', imageUrl: 'https://picsum.photos/seed/cat-info/600/400', imageHint: 'nature documentary' },
];

export function getChannels(category?: string): Channel[] {
  if (category) {
    return channels.filter(channel => channel.category.toLowerCase() === category);
  }
  return channels;
}

export function getChannelById(id: string): Channel | undefined {
  return channels.find(channel => channel.id === id);
}

export function getChannelCategory(slug: string): { name: ChannelCategory; slug: string; imageUrl: string; imageHint: string; } | undefined {
    return categories.find(cat => cat.slug === slug);
}
