
import type { Channel, ChannelCategory } from '@/lib/types';

export const channels: Channel[] = [
  {
    id: 'cbs-news',
    name: 'CBS News',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/102/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/101/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly9jYnNuLXVzLmNic25zdHJlYW0uY2JzbmV3cy5jb20vb3V0L3YxLzU1YTg2NDhlOGYxMzRlODJhNDcwZjgzZDU2MmRlZWNhL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'nick-bangla',
    name: 'NICK BANGLA',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/202/400/400',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/201/600/400',
    thumbnailImageHint: 'cartoon animation',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMTM0MS5tM3U4',
    type: 'hls',
  },
  {
    id: 'cartoon-network',
    name: 'Cartoon Network',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/402/400/400',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/401/600/400',
    thumbnailImageHint: 'cartoon characters',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfODE2Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'zb-cartoon',
    name: 'ZB Cartoon',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/502/400/400',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/501/600/400',
    thumbnailImageHint: 'cartoon fun',
    streamUrl: 'aHR0cHM6Ly9zZXJ2ZXIuemlsbGFyYmFydGEuY29tL3piY2F0dW4vdmlkZW8ubTN1OA==',
    type: 'hls',
  },
  {
    id: 'discovery-bengali',
    name: 'DISCOVERY CHANNEL BENGALI',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/602/400/400',
    logoImageHint: 'discovery logo',
    thumbnailUrl: 'https://picsum.photos/seed/601/600/400',
    thumbnailImageHint: 'nature documentary',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfNTczLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'colors-bengali-hd',
    name: 'COLORS BENGALI HD',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/702/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/701/600/400',
    thumbnailImageHint: 'drama series',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfNzU2Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'sonic-bangla',
    name: 'SONIC BANGLA',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/802/400/400',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/801/600/400',
    thumbnailImageHint: 'action cartoon',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMTM0NS5tM3U4',
    type: 'hls',
  },
  {
    id: 'tv9-bangla',
    name: 'TV9 BANGLA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/902/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/901/600/400',
    thumbnailImageHint: 'news report',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMTczNS5tM3U4',
    type: 'hls',
  },
  {
    id: 'r-bangla',
    name: 'R BANGLA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/1002/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/1001/600/400',
    thumbnailImageHint: 'breaking news',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMjc4MC5tM3U4',
    type: 'hls',
  },
  {
    id: 'rupashi-bangla',
    name: 'RUPASHI BANGLA',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/1102/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/1101/600/400',
    thumbnailImageHint: 'drama series',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMzAwNS5tM3U4',
    type: 'hls',
  },
  {
    id: 'abp-ananda',
    name: 'ABP ANANDA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/1202/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/1201/600/400',
    thumbnailImageHint: 'live news',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfNjcyLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'sangeet-bangla',
    name: 'SANGEET BANGLA',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1302/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1301/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9jZG4tNC5waXNob3cudHYvbGl2ZS8xMTQzL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'b4u-music',
    name: 'B4U Music',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1402/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1401/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9jZG5iNHUud2lzZXBsYXlvdXQuY29tL0I0VV9NdXNpYy9IRDcyMC9IRDcyMC5tM3U4',
    type: 'hls',
  },
  {
    id: '9xm',
    name: '9XM',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1502/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1501/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly85eGppby53aXNlcGxheW91dC5jb20vOVhNL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: '9x-jalwa',
    name: '9X Jalwa',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1602/400/400',
    logoImageHint: 'bollywood music',
    thumbnailUrl: 'https://picsum.photos/seed/1601/600/400',
    thumbnailImageHint: 'bollywood music',
    streamUrl: 'aHR0cHM6Ly9tdW10MDMudGFuZ290di5pbi85WEpBTFdBL3RyYWNrcy12MmExL21vbm8ubTN1OA==',
    type: 'hls',
  },
  {
    id: 'colors-bangla-cinema',
    name: 'COLORS BANGLA CINEMA',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/1702/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/1701/600/400',
    thumbnailImageHint: 'movie scene',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMTY1Ny5tM3U4',
    type: 'hls',
  },
  {
    id: 'zee-24-ghanta',
    name: 'ZEE 24 GHANTA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/1802/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/1801/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfNDY0Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'rongeen-tv',
    name: 'RONGEEN TV',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/2002/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/2001/600/400',
    thumbnailImageHint: 'colorful pattern',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMTY2Ny5tM3U4',
    type: 'hls',
  },
  {
    id: 'colors-hd',
    name: 'COLORS HD',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/2102/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/2101/600/400',
    thumbnailImageHint: 'reality show',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMTQ0Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'aaj-tak',
    name: 'AAJ TAK',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/2202/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/2201/600/400',
    thumbnailImageHint: 'news headline',
    streamUrl: 'aHR0cHM6Ly9hYWp0YWtoZGxpdmUtYW1kLmFrYW1haXplZC5uZXQvaGxzL2xpdmUvMjAxNDQxNS9hYWp0YWtoZC9hYWp0YWtoZGxpdmUvbGl2ZV83MjBwL2NodW5rcy5tM3U4',
    type: 'hls',
  },
  {
    id: 'dd-national-hd',
    name: 'DD NATIONAL HD',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/2302/400/400',
    logoImageHint: 'tv logo',
    thumbnailUrl: 'https://picsum.photos/seed/2301/600/400',
    thumbnailImageHint: 'classic show',
    streamUrl: 'aHR0cHM6Ly9kM3FzM2QycmtoZnFydC5jbG91ZGZyb250Lm5ldC9vdXQvdjEvNDA0OTJhNjRjMWRiNGExMzg1YmExYTM5N2QzNTdkM2EvaW5kZXgubTN1OA==',
    type: 'hls',
  },
  {
    id: 'dd-india',
    name: 'DD India',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/2402/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/2401/600/400',
    thumbnailImageHint: 'international news',
    streamUrl: 'aHR0cHM6Ly9kM3FzM2QycmtoZnFydC5jbG91ZGZyb250Lm5ldC9vdXQvdjEvY2VkYTE0NTgzNDc3NDI2YWExNjJhNjUzOTJkOGVhMDcvaW5kZXgubTN1OA==',
    type: 'hls',
  },
  {
    id: 'music-india',
    name: 'MUSIC INDIA',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/2502/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/2501/600/400',
    thumbnailImageHint: 'indian music',
    streamUrl: 'aHR0cHM6Ly9jZG4tMi5waXNob3cudHYvbGl2ZS8yMjYvbWFzdGVyLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'hindi-music',
    name: 'HINDI MUSIC',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/hindi-music-logo/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/hindi-music-thumb/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9jYTEuYnV4aW1lZGlhLmNvbS9pdHYvaW5kaWFuL2luZGV4Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'mtv',
    name: 'MTV',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/2602/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/2601/600/400',
    thumbnailImageHint: 'pop music',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMjQ4Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'colors-cineplex-hd',
    name: 'COLORS CINEPLEX HD',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/2702/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/2701/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMTQ3Ny5tM3U4',
    type: 'hls',
  },
  {
    id: 'animal-planet',
    name: 'ANIMAL PLANET',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/2802/400/400',
    logoImageHint: 'animal logo',
    thumbnailUrl: 'https://picsum.photos/seed/2801/600/400',
    thumbnailImageHint: 'wildlife',
    streamUrl: 'aHR0cHM6Ly92b2R6b25nLm1qdW5vb24udHY6ODA4Ny9zdHJlYW10ZXN0L0FuaW1hbC1QbGFuZXQtMTU4LTMvcGxheWxpc3QubTN1OA==',
    type: 'hls',
  },
  {
    id: 'history-tv-18-hd',
    name: 'HISTORY TV18 HD',
    category: 'Educational',
    logoUrl: 'https://picsum.photos/seed/2902/400/400',
    logoImageHint: 'history logo',
    thumbnailUrl: 'https://picsum.photos/seed/2901/600/400',
    thumbnailImageHint: 'historical document',
    streamUrl: 'aHR0cHM6Ly9hbWcwMTQ0OC1hbWcwMTQ0OGMxNi1zYW1zdW5nLWluLTM0OTUucGxheW91dHMubm93LmFtYWdpLnR2L3BsYXlsaXN0L2FtZzAxNDQ4LXNhbXN1bmdpbmRpYS1oaXN0b3J5Y2hhbm5lbGVuZ2xpc2gtc2Ftc3VuZ2luL3BsYXlsaXN0Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'dd-kisan',
    name: 'DD KISAN',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/3002/400/400',
    logoImageHint: 'farming logo',
    thumbnailUrl: 'https://picsum.photos/seed/3001/600/400',
    thumbnailImageHint: 'agriculture field',
    streamUrl: 'aHR0cHM6Ly9jZG4tNi5waXNob3cudHYvbGl2ZS85L21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'dangal',
    name: 'DANGAL',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/3202/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/3201/600/400',
    thumbnailImageHint: 'indian drama',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfNzAxLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'b4u-kadak',
    name: 'B4U KADAK',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/3302/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/3301/600/400',
    thumbnailImageHint: 'action movie',
    streamUrl: 'aHR0cHM6Ly9jZG5iNHUud2lzZXBsYXlvdXQuY29tL0I0VV9LYWRhay9IRDcyMC9IRDcyMC5tM3U4',
    type: 'hls',
  },
  {
    id: 'dd-sports',
    name: 'DD SPORTS',
    category: 'Sports',
    logoUrl: 'https://picsum.photos/seed/3402/400/400',
    logoImageHint: 'sports logo',
    thumbnailUrl: 'https://picsum.photos/seed/3401/600/400',
    thumbnailImageHint: 'cricket match',
    streamUrl: 'aHR0cHM6Ly9jZG4tNi5waXNob3cudHYvbGl2ZS8xMy9tYXN0ZXIubTN1OA==',
    type: 'hls',
  },
  {
    id: 'wion',
    name: 'WION',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/3502/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/3501/600/400',
    thumbnailImageHint: 'world news',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfNDEyLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'pogo',
    name: 'POGO',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/3602/400/400',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/3601/600/400',
    thumbnailImageHint: 'kids cartoon',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfNTU5Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'goldmines',
    name: 'GOLDMINES',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/4002/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/4001/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'aHR0cHM6Ly9jZG4tMi5waXNob3cudHYvbGl2ZS8xNDU5L21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'green-gold-tv',
    name: 'Green Gold Tv',
    category: 'Kids',
    logoUrl: 'https://images.unsplash.com/photo-1512529920731-e8abaea917a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxraWRzJTIwbG9nb3xlbnwwfHx8fDE3Njg5MjE0NDN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://images.unsplash.com/photo-1758789887939-dea05e990b48?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxjYXJ0b29uJTIwc2hvd3xlbnwwfHx8fDE3Njg5MjE0NDN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    thumbnailImageHint: 'cartoon show',
    streamUrl: 'aHR0cHM6Ly92Z2xpdmVzc2FpLmFrYW1haXplZC5uZXQvcHRuci15dXBwdHYvdGl0bGUtR3JlZW5fR29sZF9JbmRpYS9ldS92MS9tYXN0ZXIvNjExZDc5YjExYjc3ZTJmNTcxOTM0ZmQ4MGNhMTQxMzQ1Mzc3MmFjNy82NzVhMzdlNS1mNTE3LTQzNGUtYWRhZS1kMjVhZTE3MDYzNDAvcGxheWxpc3QubTN1OA==',
    type: 'hls',
  },
  {
    id: 'yrf-music',
    name: 'YRF Music',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/4402/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/4401/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9kMzVqNTA0ejB4MnZ1Mi5jbG91ZGZyb250Lm5ldC92MS9tYW5pZmVzdC8wYmM4ZTgzNzZiZDg0MTdhMWI2NzYxMTM4YWE0MWMyNmM3MzA5MzEyL3lyZi1tdXNpYy9tYXN0ZXIubTN1OA==',
    type: 'hls',
  },
  {
    id: 'shemaroo-filmi-gaane',
    name: 'Shemaroo Filmi Gaane',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/4502/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/4501/600/400',
    thumbnailImageHint: 'bollywood music',
    streamUrl: 'aHR0cHM6Ly9kMzVqNTA0ejB4MnZ1Mi5jbG91ZGZyb250Lm5ldC92MS9tYW5pZmVzdC8wYmM4ZTgzNzZiZDg0MTdhMWI2NzYxMTM4YWE0MWMyNmM3MzA5MzEyL3NoZW1hcm9vLWZpbG1pZ2FhbmUvNWEyYjJmNDktOTIyOS00ZGE2LWJhODUtZDNlZTk3NzNjYjdmLzAubTN1OA==',
    type: 'hls',
  },
  {
    id: 'republic',
    name: 'REPUBLIC',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/5202/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/5201/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly9kM3FzM2QycmtoZnFydC5jbG91ZGZyb250Lm5ldC9vdXQvdjEvMmUzMWQ4MzFmMDg2NDBmZjkyZjY1MDAzYmRjODk5OTEvaW5kZXhfNS5tM3U4',
    type: 'hls',
  },
  {
    id: 'sangeet-bhojpuri',
    name: 'SANGEET BHOJPURI',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/5302/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/5301/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9jZG4tNC5waXNob3cudHYvbGl2ZS8xMjkzL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'zoom',
    name: 'ZOOM',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/5402/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/5401/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9kYWkuZ29vZ2xlLmNvbS9saW5lYXIvaGxzL2V2ZW50L0pDQW0yNXFrUlhpS2NLMUFKTWx2S1EvbWFzdGVyLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'shemaroo-bollywood',
    name: 'SHEMAROO BOLLYWOOD',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/5602/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/5601/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'aHR0cHM6Ly9kMzVqNTA0ejB4MnZ1Mi5jbG91ZGZyb250Lm5ldC92MS9tYW5pZmVzdC8wYmM4ZTgzNzZiZDg0MTdhMWI2NzYxMTM4YWE0MWMyNmM3MzA5MzEyL3NoZW1hcm9vLWJvbGx5d29vZC9jYTU1MzczNS1lOTA4LTRmNzUtYThjZC03MDVjM2MyMmZjYjIvMC5tM3U4',
    type: 'hls',
  },
  {
    id: 'cine-jomjomat',
    name: 'Cine Jomjomat',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/6102/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/6101/600/400',
    thumbnailImageHint: 'movie scene',
    streamUrl: 'aHR0cHM6Ly9hbWcxMzc3OS1hbWcxMzc3OWMxLWFtZ3BsdDAxNzMucGxheW91dC5ub3czLmFtYWdpLnR2L3RzLWV1LXcxLW4yL3BsYXlsaXN0L2FtZzEzNzc5LWFtZzEzNzc5YzEtYW1ncGx0MDE3My9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'goldmines-movies',
    name: 'GOLDMINES MOVIES',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/6202/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/6201/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'aHR0cHM6Ly9jZG4tMi5waXNob3cudHYvbGl2ZS8xNDYxLzE0NjFfMS5tM3U4',
    type: 'hls',
  },
  {
    id: 'south-station',
    name: 'SOUTH STATION',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/south-station-logo/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/south-station-thumb/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9jYy15dzd6dGVjeThkbzNxLmFrYW1haXplZC5uZXQvdjEvbWFzdGVyLzM3MjJjNjBhODE1YzE5OWQ5YzBlZjM2YzViNzNkYTY4YTYyYjA5ZDEvY2MteXc3enRlY3k4ZG8zcS9TU19JTi5tM3U4',
    type: 'hls',
  },
  {
    id: 'fresh-movies',
    name: 'Fresh Movies',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/fresh-movies-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/fresh-movies-thumb/600/400',
    thumbnailImageHint: 'movie scene',
    streamUrl: 'aHR0cHM6Ly9hbWcwMjQxMS12dnNmaWxtcy1hbWcwMjQxMWMxLWxnLWNhLTk2NTQucGxheW91dHMubm93LmFtYWdpLnR2L3BsYXlsaXN0L2FtZzAyNDExLXZ2c2ZpbG1zLWZyZXNobW92aWVzLWxnY2EvcGxheWxpc3QubTN1OA==',
    type: 'hls',
  },
  {
    id: 'popular-science',
    name: 'Popular Science',
    category: 'Educational',
    logoUrl: 'https://picsum.photos/seed/popular-science-logo/400/400',
    logoImageHint: 'science logo',
    thumbnailUrl: 'https://picsum.photos/seed/popular-science-thumb/600/400',
    thumbnailImageHint: 'science technology',
    streamUrl: 'aHR0cHM6Ly9hbWcxMzIzMS1hY3R2ZS1hbWcxMzIzMWM1LWtvZ2FuLWF1LTExMjc2LnBsYXlvdXRzLm5vdy5hbWFnaS50di90cy1ldS13MS1uMi9wbGF5bGlzdC9hbWcxMzIzMS1hY3R2ZWZhc3QtcG9wdWxhcnNjaWVuY2Uta29nYW5hdS9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'cine-life',
    name: 'Cine Life',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/cine-life-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/cine-life-thumb/600/400',
    thumbnailImageHint: 'movie scene',
    streamUrl: 'aHR0cHM6Ly9jZG4tdXcyLXByb2QudHN2Mi5hbWFnaS50di9saW5lYXIvYW1nMDAzMDgtbWFnbm9saWFwaWN0dXJlLWNpbmVsaWZlLXRjbC9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'shemaroo-josh',
    name: 'SHEMAROO JOSH',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/7002/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/7001/600/400',
    thumbnailImageHint: 'movie scene',
    streamUrl: 'aHR0cHM6Ly9haXJ0ZWxhcHAuc2hlbWFyb28uY29tL3NoZW1hcm9vQ2h1bWJha1RWL3NtaWw6c2hlbWFyb29DaHVtYmFrVFZhZHAuc21pbC9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'mix-hollywood',
    name: 'MIX HOLLYWOOD',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/7202/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/7201/600/400',
    thumbnailImageHint: 'hollywood movie',
    streamUrl: 'aHR0cHM6Ly9tbC1wdWxsLWh3Yy5teWNvLmlvL01peFRWL2hscy9NaXhUVl9IMjY0LTEwODBwLm0zdTg/cGtnX21lZGlhPXZpZGVvJnBrZ19obT1pbmRleC5tM3U4JnBrZ19zdmM9MSZwa2dfdmNvZGVjPWF2YzE=',
    type: 'hls',
  },
  {
    id: 'z-south-flix',
    name: 'Z SOUTH FLIX',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/7502/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/7501/600/400',
    thumbnailImageHint: 'south indian movie',
    streamUrl: 'aHR0cHM6Ly9hbWcwMDg2Mi1hbWcwMDg2MmM5LWFtZ3BsdDAxNzMucGxheW91dC5ub3czLmFtYWdpLnR2L3BsYXlsaXN0L2FtZzAwODYyLWFtZzAwODYyYzktYW1ncGx0MDE3My9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'z-cine-classic',
    name: 'Z CINE CLASSIC',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/7602/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/7601/600/400',
    thumbnailImageHint: 'classic movie',
    streamUrl: 'aHR0cHM6Ly9hbWcwMDg2Mi1hbWcwMDg2MmM4LWFtZ3BsdDAxNzMucGxheW91dC5ub3czLmFtYWdpLnR2L3BsYXlsaXN0L2FtZzAwODYyLWFtZzAwODYyYzgtYW1ncGx0MDE3My9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'bollywood-classic',
    name: 'BOLLYWOOD CLASSIC',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/8102/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/8101/600/400',
    thumbnailImageHint: 'classic bollywood',
    streamUrl: 'aHR0cHM6Ly9kMzVqNTA0ejB4MnZ1Mi5jbG91ZGZyb250Lm5ldC92MS9tYW5pZmVzdC8wYmM4ZTgzNzZiZDg0MTdhMWI2NzYxMTM4YWE0MWMyNmM3MzA5MzEyL2JvbGx5d29vZC1jbGFzc2ljL2NkZWUzZTcyLTIzZDctNGVlMC1iYWZhLWIxYTYyODMyZWU4NS8wLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'nh-bolly-flix',
    name: 'NH BOLLY FLIX',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/8202/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/8201/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'aHR0cHM6Ly9jYy1yNWh1cGN5bTVvZWhoLmFrYW1haXplZC5uZXQvdjEvbWFuaWZlc3QvMzcyMmM2MGE4MTVjMTk5ZDljMGVmMzZjNWI3M2RhNjhhNjJiMDlkMS9jYy1yNWh1cGN5bTVvZWhoLzhmMGE5M2ExLThkMTYtNDhlOS04OGViLTU0ZGViMmJjM2M0Zi8wLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'all-time-movies',
    name: 'ALL TIME MOVIES',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/8402/400/400',
    logoImageHint: 'classic movies',
    thumbnailUrl: 'https://picsum.photos/seed/8401/600/400',
    thumbnailImageHint: 'classic movie',
    streamUrl: 'aHR0cHM6Ly9tdW10MDMudGFuZ290di5pbi9BTExUSU1FTU9WSUVTL3RyYWNrcy12MmExL21vbm8ubTN1OA==',
    type: 'hls',
  },
  {
    id: 'gubbare',
    name: 'GUBBARE',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/gubbare-logo/400/400',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/gubbare-thumb/600/400',
    thumbnailImageHint: 'kids cartoon',
    streamUrl: 'aHR0cHM6Ly9lcGljb252aC5ha2FtYWl6ZWQubmV0L2xpdmUvZ3ViYmFyZS9tYXN0ZXIubTN1OA==',
    type: 'hls',
  },
  {
    id: 'pbs-science',
    name: 'PBS SCIENCE',
    category: 'Educational',
    logoUrl: 'https://picsum.photos/seed/pbs-science-logo/400/400',
    logoImageHint: 'science logo',
    thumbnailUrl: 'https://picsum.photos/seed/pbs-science-thumb/600/400',
    thumbnailImageHint: 'science documentary',
    streamUrl: 'aHR0cHM6Ly9hbWcwMjMzMy1wYnMtYW1nMDIzMzNjMTMtc2Ftc3VuZy1hdS02ODU4LnBsYXlvdXRzLm5vdy5hbWFnaS50di9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'nature-time',
    name: 'NATURE TIME',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/nature-time-logo/400/400',
    logoImageHint: 'nature logo',
    thumbnailUrl: 'https://picsum.photos/seed/nature-time-thumb/600/400',
    thumbnailImageHint: 'nature documentary',
    streamUrl: 'aHR0cHM6Ly9jZG4tdXcyLXByb2QudHN2Mi5hbWFnaS50di9saW5lYXIvYW1nMDAwOTAtYmx1ZWFudGxsYy1sb3ZlbmF0dXJlLWF1LXNhbXN1bmdhdS9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'akaash-aath',
    name: 'AKAASH AATH',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/akaash-aath-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/akaash-aath-thumb/600/400',
    thumbnailImageHint: 'bengali show',
    streamUrl: 'aHR0cHM6Ly9jZG4tNC5waXNob3cudHYvbGl2ZS85NjkvbWFzdGVyLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'orange-bangla',
    name: 'ORANGE BANGLA',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/orange-bangla-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/orange-bangla-thumb/600/400',
    thumbnailImageHint: 'bengali show',
    streamUrl: 'aHR0cHM6Ly9jZG4tNC5waXNob3cudHYvbGl2ZS8xNDk5L21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'news-18-bangla',
    name: 'NEWS 18 BANGLA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/news-18-bangla-logo/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/news-18-bangla-thumb/600/400',
    thumbnailImageHint: 'bengali news',
    streamUrl: 'aHR0cHM6Ly9udzE4bGl2ZS5jZG4uamlvLmNvbS9icGstdHYvTmV3czE4X0JhbmdsYV9OVzE4X01PQi9vdXRwdXQwMS9pbmRleC5tM3U4',
    type: 'hls',
  },
  {
    id: 'b4u-movies',
    name: 'B4U MOVIES',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/b4u-movies-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/b4u-movies-thumb/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'aHR0cHM6Ly9jZG5iNHUud2lzZXBsYXlvdXQuY29tL0I0VV9Nb3ZpZXMvSEQ3MjAvSEQ3MjAubTN1OA==',
    type: 'hls',
  },
  {
    id: 'abzy-movies',
    name: 'ABZY MOVIES',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/abzy-movies-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/abzy-movies-thumb/600/400',
    thumbnailImageHint: 'movie poster',
    streamUrl: 'aHR0cHM6Ly9kM3FzM2QycmtoZnFydC5jbG91ZGZyb250Lm5ldC9vdXQvdjEvZGI4ZDRlY2E3MmQ2NDc0OGEwMGQwNjMxZGViZjU0MmQvaW5kZXgubTN1OA==',
    type: 'hls',
  },
  {
    id: 'showbox',
    name: 'SHOWBOX',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/showbox-logo/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/showbox-thumb/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9lcGljb252aC5ha2FtYWl6ZWQubmV0L2xpdmUvc2hvd2JveC9tYXN0ZXIubTN1OA==',
    type: 'hls',
  },
  {
    id: 'discovery-asia',
    name: 'DISCOVERY ASIA',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/discovery-asia-logo/400/400',
    logoImageHint: 'discovery logo',
    thumbnailUrl: 'https://picsum.photos/seed/discovery-asia-thumb/600/400',
    thumbnailImageHint: 'asia documentary',
    streamUrl: 'aHR0cHM6Ly9jZG4xLnNreWdvLm1uL2xpdmUvZGlzazEvRGlzY292ZXJ5X0FzaWEvSExTdjMtRlRBL0Rpc2NvdmVyeV9Bc2lhLWF2YzFfMzAwMDAwMD02Ny1tcDRhXzI1NjAwMF9lbmc9MTIubTN1OA==',
    type: 'hls',
  },
  {
    id: 'love-the-planet',
    name: 'LOVE THE PLANET',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/love-planet-logo/400/400',
    logoImageHint: 'planet earth',
    thumbnailUrl: 'https://picsum.photos/seed/love-planet-thumb/600/400',
    thumbnailImageHint: 'earth documentary',
    streamUrl: 'aHR0cHM6Ly9hbWcwMTgyMS1sb3ZldHZjaGFubmVscy1sb3ZldGhlcGxhbmV0dWtzYW1zdW5nLXNhbXN1bmd1ay1hcG9wdy5hbWFnaS50di90cy1ldS13MS1uMi9wbGF5bGlzdC9hbWcwMTgyMS1sb3ZldHZjaGFubmVscy1sb3ZldGhlcGxhbmV0dWtzYW1zdW5nLXNhbXN1bmd1ay9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'bbc-earth',
    name: 'BBC EARTH',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/bbc-earth-logo/400/400',
    logoImageHint: 'earth logo',
    thumbnailUrl: 'https://picsum.photos/seed/bbc-earth-thumb/600/400',
    thumbnailImageHint: 'nature documentary',
    streamUrl: 'aHR0cHM6Ly9kM3UzcGZoaHZ1YWQ5ay5jbG91ZGZyb250Lm5ldC9wbGF5bGlzdC9hbWcwMDc5My1iYmNzdHVkaW9zLWJiY2VhcnRhLWxndXMvcGxheWxpc3QubTN1OA==',
    type: 'hls',
  },
  {
    id: 'food-food',
    name: 'FOOD FOOD',
    category: 'Lifestyle',
    logoUrl: 'https://picsum.photos/seed/food-food-logo/400/400',
    logoImageHint: 'food logo',
    thumbnailUrl: 'https://picsum.photos/seed/food-food-thumb/600/400',
    thumbnailImageHint: 'cooking show',
    streamUrl: 'aHR0cHM6Ly9tdW10MDMudGFuZ290di5pbi9GT09ERk9PRC90cmFja3MtdjJhMS9tb25vLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'epic',
    name: 'EPIC',
    category: 'Educational',
    logoUrl: 'https://picsum.photos/seed/epic-logo/400/400',
    logoImageHint: 'epic logo',
    thumbnailUrl: 'https://picsum.photos/seed/epic-thumb/600/400',
    thumbnailImageHint: 'historical epic',
    streamUrl: 'aHR0cHM6Ly9lcGljb252aC5ha2FtYWl6ZWQubmV0L2xpdmUvZXBpYy9tYXN0ZXIubTN1OA==',
    type: 'hls',
  },
  {
    id: 'nh-bollygold',
    name: 'NH BOLLYGOLD',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/nh-bollygold-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/nh-bollygold-thumb/600/400',
    thumbnailImageHint: 'bollywood classic',
    streamUrl: 'aHR0cHM6Ly9jc20tZS1ydW5udHZwcmRsaXZlLWViLnJ1bm5hZHMucnVubi5tZWRpYS9jc20vZXh0bGl2ZS9ydW5udHZwcmQwMSxuaGJvbGx5Z29sZG90dHBsYXkubTN1OA==',
    type: 'hls',
  },
  {
    id: 'runn-tv',
    name: 'RUNN TV',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/runn-tv-logo/400/400',
    logoImageHint: 'tv logo',
    thumbnailUrl: 'https://picsum.photos/seed/runn-tv-thumb/600/400',
    thumbnailImageHint: 'tv show',
    streamUrl: 'aHR0cHM6Ly9lMDdiNjE2OTZhOGU0ZDZkOWJiY2I5NGIxNWZjOGI0ZS5tZWRpYXRhaWxvci5hcC1zb3V0aC0xLmFtYXpvbmF3cy5jb20vdjEvbWFzdGVyL2QzNjdmOWI4NjNhN2EwNDgyN2Y3MWVjYWI0Y2JlZWIxMWY3OGE4MjcvY2luc2hmLWFpcnRlbC9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'dhamaka-movies',
    name: 'DHAMAKA MOVIES',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/dhamaka-movies-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/dhamaka-movies-thumb/600/400',
    thumbnailImageHint: 'action movie',
    streamUrl: 'aHR0cHM6Ly9jZG4tMS5waXNob3cudHYvbGl2ZS8yMzUvbWFzdGVyLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'goldmines-2',
    name: 'GOLDMINES 2',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/goldmines-2-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/goldmines-2-thumb/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'aHR0cHM6Ly9jZG4tMi5waXNob3cudHYvbGl2ZS8xNDYwL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'dd-news',
    name: 'DD NEWS',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/dd-news-logo/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/dd-news-thumb/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly93d3cueW91dHViZS1ub2Nvb2tpZS5jb20vZW1iZWQvVHhvQVlXZzY0QW8/c2k9dElxU0xMSXlYU2djS2JqYw==',
    type: 'iframe',
  },
  {
    id: 'best-action',
    name: 'BEST ACTION',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/best-action-logo/400/400',
    logoImageHint: 'action movie',
    thumbnailUrl: 'https://picsum.photos/seed/best-action-thumb/600/400',
    thumbnailImageHint: 'action scene',
    streamUrl: 'aHR0cHM6Ly9zdHJlYW1zMi5zb2Zhc3QudHYvcHRuci15dXBwdHYvdGl0bGUtQkVTVF9BQ1RJT05fWVVQUFRWL3YxL21hbmlmZXN0LzYxMWQ3OWIxMWI3N2UyZjU3MTkzNGZkODBjYTE0MTM0NTM3NzJhYzcvOWE0YTU0MTItY2E5OS00OGQzLTkwMTMtZDE4MTFiOTViOWQyL2I0OWJkNGIxLWVlNDUtNDA3My1hYmY1LWYwMzhjMjYzNWJhNC8yLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'bangla-plus',
    name: 'Bangla Plus',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/bangla-plus-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/bangla-plus-thumb/600/400',
    thumbnailImageHint: 'bengali show',
    streamUrl: 'aHR0cHM6Ly9saXZlLXN0cmVhbS51dGthbGJvbmdvLmNvbS9obHMvbGl2ZWJhbmdsYXR2c3RyZWFtLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'joo-music',
    name: 'JOO MUSIC',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/joo-music-logo/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/joo-music-thumb/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9saXZlY2RuLmxpdmUyNDdzdHJlYW0uY29tL2pvb211c2ljL3R2L3BsYXlsaXN0Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'enterr-10-bangla',
    name: 'Enterr 10 Bangla',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/enterr-10-bangla-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/enterr-10-bangla-thumb/600/400',
    thumbnailImageHint: 'bengali show',
    streamUrl: 'aHR0cHM6Ly9saXZlLWJhbmdsYS5ha2FtYWl6ZWQubmV0L2xpdmVhYnIvcGxheWxpc3QubTN1OA==',
    type: 'hls',
  },
  {
    id: 'hi-dost',
    name: 'Hi Dost',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/hi-dost-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/hi-dost-thumb/600/400',
    thumbnailImageHint: 'tv show',
    streamUrl: 'aHR0cHM6Ly9jZG4tMS5waXNob3cudHYvbGl2ZS8yMjQvbWFzdGVyLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'khushboo-bangla',
    name: 'KHUSHBOO BANGLA',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/khushboo-bangla-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/khushboo-bangla-thumb/600/400',
    thumbnailImageHint: 'bengali show',
    streamUrl: 'aHR0cHM6Ly9jZG4tNC5waXNob3cudHYvbGl2ZS8xNDczL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'zb-music',
    name: 'ZB MUSIC',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/zb-music-logo/400/400',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/zb-music-thumb/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'aHR0cHM6Ly9zZXJ2ZXIuemlsbGFyYmFydGEuY29tL3pibXVzaWMvdHJhY2tzLXYxYTEvbW9uby50cy5tM3U4',
    type: 'hls',
  },
  {
    id: 'zb-bhakti',
    name: 'ZB BHAKTI',
    category: 'Devotional',
    logoUrl: 'https://picsum.photos/seed/zb-bhakti-logo/400/400',
    logoImageHint: 'spiritual logo',
    thumbnailUrl: 'https://picsum.photos/seed/zb-bhakti-thumb/600/400',
    thumbnailImageHint: 'devotional music',
    streamUrl: 'aHR0cHM6Ly9zZXJ2ZXIuemlsbGFyYmFydGEuY29tL3piYmhha3RpL2luZGV4Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'ananda-barta',
    name: 'ANANDA BARTA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/ananda-barta-logo/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/ananda-barta-thumb/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly9hY2NvdW50MTkubGl2ZWJveC5jby5pbi9BbmFuZGFiYXJ0YTJobHMvbGl2ZS5tM3U4',
    type: 'hls',
  },
  {
    id: 'sun-tv',
    name: 'Sun TV',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/sun-tv-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/sun-tv-thumb/600/400',
    thumbnailImageHint: 'tv show',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfMTY2OS5tM3U4',
    type: 'hls',
  },
  {
    id: '24-hrs-tv',
    name: '24 Hrs TV',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/24-hrs-tv-logo/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/24-hrs-tv-thumb/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly9zZXJ2ZXIubGl2ZWxlZ2l0cHJvLmluLzI0aG91cnN0di8yNGhvdXJzdHYvaW5kZXgubTN1OA==',
    type: 'hls',
  },
  {
    id: 'r-plus-gold',
    name: 'R Plus Gold',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/r-plus-gold-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/r-plus-gold-thumb/600/400',
    thumbnailImageHint: 'tv show',
    streamUrl: 'aHR0cHM6Ly9jZG4tNC5waXNob3cudHYvbGl2ZS8xMjMxL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'nktv-bangla',
    name: 'NKTV Bangla',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/nktv-bangla-logo/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/nktv-bangla-thumb/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly9ua3R2LnNtYXJ0c3RyZWFtLnZpZGVvL3NtYXJ0c3RyZWFtLXVzL25rYmFuZ2xhL25rYmFuZ2xhL3BsYXlsaXN0Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'bangla-jago',
    name: 'Bangla Jago',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/bangla-jago-logo/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/bangla-jago-thumb/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly9iYW5nbGFqYWdvdHYubGl2ZWJveC5jby5pbi9iYW5nbGFqYWdvaGxzLzI0eDcubTN1OA==',
    type: 'hls',
  },
  {
    id: 'rokuten-scitv',
    name: 'Rokuten SciTV',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/rokuten-scitv-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/rokuten-scitv-thumb/600/400',
    thumbnailImageHint: 'sci-fi movie',
    streamUrl: 'aHR0cHM6Ly9zY2ktZmktcmFrdXRlbi10di11ay5mYXN0LnJha3V0ZW4udHYvdjEvbWFzdGVyLzA1NDdmMTg2NDliZDc4OGJlYzdiNjdiNzQ2ZTQ3NjcwZjU1OGI2YjIvcHJvZHVjdGlvbi1MaXZlQ2hhbm5lbC02MjQxL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'xumo-tv',
    name: 'Xumo Tv',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/xumo-tv-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/xumo-tv-thumb/600/400',
    thumbnailImageHint: 'movie screen',
    streamUrl: 'aHR0cHM6Ly9kM2ZtcWk5MXFkdWo3LmNsb3VkZnJvbnQubmV0LzExNDAxLzg4ODE0NTM1L2hscy9tYXN0ZXIubTN1OD9hZHMueHVtb19jaGFubmVsSWQ9ODg4MTQ1MzUmYWRzLnh1bW9fc3RyZWFtSWQ9ODg4MTQ1MzU=',
    type: 'hls',
  },
  {
    id: 'plex-rush',
    name: 'Plex Rush',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/plex-rush-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/plex-rush-thumb/600/400',
    thumbnailImageHint: 'action movie',
    streamUrl: 'aHR0cHM6Ly80MzZmNTk1Nzk0MzY0NzNlODE2ODI4NGNhYzVkNzI1Zi5tZWRpYXRhaWxvci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbS92MS9tYXN0ZXIvNDRmNzNiYTRkMDNlOTYwN2RjZDliZWJkY2I4NDk0ZDg2OTY0ZjFkOC9QbGV4X1J1c2hCeUFNQy9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'rakuten-tv',
    name: 'Rakuten TV',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/rakuten-tv-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/rakuten-tv-thumb/600/400',
    thumbnailImageHint: 'movie collection',
    streamUrl: 'aHR0cHM6Ly85YmU3ODNkNjUyY2Q0YjA5OWNmNjNlMWRjMTM0YzRhMy5tZWRpYXRhaWxvci5ldS13ZXN0LTEuYW1hem9uYXdzLmNvbS92MS9tYXN0ZXIvMDU0N2YxODY0OWJkNzg4YmVjN2I2N2I3NDZlNDc2NzBmNTU4YjZiMi9wcm9kdWN0aW9uLUxpdmVDaGFubmVsLTYxODEvbWFzdGVyLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'next-g-tv',
    name: 'Next G TV',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/next-g-tv-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/next-g-tv-thumb/600/400',
    thumbnailImageHint: 'movie poster',
    streamUrl: 'aHR0cHM6Ly9tb3ZpZXMubmV4Zy50di9tb3ZpZS1oL21vdmllLWguc21pbC9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'free-movies',
    name: 'Free Movies',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/free-movies-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/free-movies-thumb/600/400',
    thumbnailImageHint: 'film strip',
    streamUrl: 'aHR0cHM6Ly9hbWcwMTU1My1hbWcwMTU1M2MyLXNhbXN1bmctdGgtNzE2NC5wbGF5b3V0cy5ub3cuYW1hZ2kudHYvcGxheWxpc3QubTN1OA==',
    type: 'hls',
  },
  {
    id: 'sony-movies',
    name: 'Sony Movies',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/sony-movies-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/sony-movies-thumb/600/400',
    thumbnailImageHint: 'movie premiere',
    streamUrl: 'aHR0cHM6Ly9hLWNkbi5rbG93ZHR2LmNvbS9saXZlMS9zbWNfNzIwcC9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  {
    id: 'the-movie-club',
    name: 'The Movie Club',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/the-movie-club-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/the-movie-club-thumb/600/400',
    thumbnailImageHint: 'movie scene',
    streamUrl: 'aHR0cHM6Ly9zaXMtZ2xvYmFsLnByb2Quc2Ftc3VuZ3R2LnBsdXMvdjEvdHZwcHJkL3NjLW1wMmFyNGNhNDI1eG8ubTN1OA==',
    type: 'hls',
  },
  {
    id: 'travel-4k',
    name: 'Travel 4K',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/travel-4k-logo/400/400',
    logoImageHint: 'travel logo',
    thumbnailUrl: 'https://picsum.photos/seed/travel-4k-thumb/600/400',
    thumbnailImageHint: 'travel 4k',
    streamUrl: 'aHR0cHM6Ly9zdHJlYW1zMi5zb2Zhc3QudHYvcHRuci1sZ3R2L3RpdGxlLTRLLVRSQVZFTC1UVi1FTkdfTEcvdjEvbWFzdGVyLzYxMWQ3OWIxMWI3N2UyZjU3MTkzNGZkODBjYTE0MTM0NTM3NzJhYzcvZjkyYWI4YzQtNDg5Ny00NmFkLThkYTAtZDA5ZDRhOWJiMjVmL21hbmlmZXN0Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'horray-rhymes',
    name: 'HORRAY RHYMES',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/horray-rhymes-logo/400/400',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/horray-rhymes-thumb/600/400',
    thumbnailImageHint: 'kids rhymes',
    streamUrl: 'aHR0cHM6Ly9xbi0wMTI3My1wb2wtMS0wMS0xLS0tNzI0Ny1hbXlwLmh0dHAuZ2xvYmFsLmRucy5xd2lsdGVkLWNkcy5jcWxvdWQuY29tL09UTS9PVE1fS2lkc1Rvb25zSGluZGktU0NURV9DRE4vcGxheWxpc3QubTN1OA==',
    type: 'hls',
  },
  {
    id: 'hollywood-desi',
    name: 'HOLLYWOOD DESI',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/hollywood-desi-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/hollywood-desi-thumb/600/400',
    thumbnailImageHint: 'hollywood movie',
    streamUrl: 'aHR0cHM6Ly9jYy11NmhhZG5vaDB1NnRkLmFrYW1haXplZC5uZXQvdjEvbWFzdGVyLzM3MjJjNjBhODE1YzE5OWQ5YzBlZjM2YzViNzNkYTY4YTYyYjA5ZDEvY2MtdTZoYWRub2gwZDZ0ZC9PVE0vT1RNX0hvbGx5d29vZEFjdGlvbkhpbmRpLVNDVEVfU0FNU1VORy9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
  // Sony Channels and iframe channels at the bottom as requested
  {
    id: 'discovery-science',
    name: 'Discovery Science',
    category: 'Educational',
    logoUrl: 'https://picsum.photos/seed/discovery-science-logo/400/400',
    logoImageHint: 'science technology',
    thumbnailUrl: 'https://picsum.photos/seed/discovery-science-thumb/600/400',
    thumbnailImageHint: 'science experiment',
    streamUrl: 'aHR0cHM6Ly9hbWcwMDEzNi13YmQtYW1nMDAxMzZjMjAtdGFibG8tdXMtNzE5MC5wbGF5b3V0cy5ub3cuYW1hZ2kudHYvcGxheWxpc3Q3MjBwLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'sony',
    name: 'SONY',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/302/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/301/600/400',
    thumbnailImageHint: 'red carpet',
    streamUrl: 'aHR0cHM6Ly9taW5pLmFsbGlub25lcmVib3JuLmZ1bi9qaW90di1pbm4vYXBwL3RzX2xpdmVfNTUxLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'star-jalsha-hd',
    name: 'Star Jalsha HD',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/star-jalsha-hd-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/star-jalsha-hd-thumb/600/400',
    thumbnailImageHint: 'bengali drama',
    streamUrl: 'aHR0cHM6Ly90dnNlbjEuYXluYW90dC5jb20vZ1VYOEJKbU5jMnlGL2luZGV4Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'zee-cinema-usa',
    name: 'Zee Cinema USA',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/zee-cinema-usa-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/zee-cinema-usa-thumb/600/400',
    thumbnailImageHint: 'bollywood movie',
    streamUrl: 'aHR0cHM6Ly9hbWcxNzkzMS16ZWUtYW1nMTc5MzFjNS1rb2dhbi1hdS05NTIxLnBsYXlvdXRzLm5vdy5hbWFnaS50di90cy1ldS13MS1uMi9wbGF5bGlzdC9hbWcxNzkzMS1hc2lhdHZ1c2FsdGRmYXN0LXplZWNpbmVtYS1rb2dhbmF1L3BsYXlsaXN0Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'zb-cinema',
    name: 'ZB CINEMA',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/zb-cinema-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/zb-cinema-thumb/600/400',
    thumbnailImageHint: 'bengali movie',
    streamUrl: 'aHR0cHM6Ly9zZXJ2ZXIuemlsbGFyYmFydGEuY29tL1pCQ0lORU1BL2luZGV4Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'dd-bangla',
    name: 'DD BANGLA',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/dd-bangla-logo/400/400',
    logoImageHint: 'tv logo',
    thumbnailUrl: 'https://picsum.photos/seed/dd-bangla-thumb/600/400',
    thumbnailImageHint: 'bengali show',
    streamUrl: 'aHR0cHM6Ly9kM3FzM2QycmtoZnFydC5jbG91ZGZyb250Lm5ldC9vdXQvdjEvN2ZmNTdjYzkwNDZiNGMxODhiNTFhMGQ1MDZmMzZlN2YvaW5kZXgubTN1OA==',
    type: 'hls',
  },
  {
    id: 'ctvn',
    name: 'CTVN',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/ctvn-logo/400/400',
    logoImageHint: 'tv logo',
    thumbnailUrl: 'https://picsum.photos/seed/ctvn-thumb/600/400',
    thumbnailImageHint: 'live show',
    streamUrl: 'aHR0cHM6Ly93d3cueW91dHViZS5jb20vZW1iZWQvLWtMQWNtckNtS00=',
    type: 'iframe',
  },
  {
    id: 'high-news',
    name: 'High News',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/high-news-2-logo/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/high-news-2-thumb/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly9oaWdobWVkaWEubGl2ZWJveC5jby5pbi9ISUdITkVXU2hscy9MSVZFLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'nazara-tv',
    name: 'Nazara TV',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/nazara-tv-logo/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/nazara-tv-thumb/600/400',
    thumbnailImageHint: 'tv show',
    streamUrl: 'aHR0cHM6Ly9kMjgyYTdyenBibDBuai5jbG91ZGZyb250Lm5ldC9saXZlL25hemFyYS9tYXN0ZXIubTN1OA==',
    type: 'hls',
  },
  {
    id: 'big-magic',
    name: 'BIG MAGIC',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/9002/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/9001/600/400',
    thumbnailImageHint: 'magic show',
    streamUrl: 'aHR0cHM6Ly9tdW10MDUudGFuZ290di5pbi9CSUdNQUdJQy9pbmRleC5tM3U4',
    type: 'hls',
  },
  {
    id: 'manoranjan-grand',
    name: 'MANORANJAN GRAND',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/9022/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/9021/600/400',
    thumbnailImageHint: 'grand show',
    streamUrl: 'aHR0cHM6Ly9jZG4tMS5waXNob3cudHYvbGl2ZS8xMDExL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'manoranjan-tv',
    name: 'MANORANJAN TV',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/9032/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/9031/600/400',
    thumbnailImageHint: 'tv serial',
    streamUrl: 'aHR0cHM6Ly9jZG4tMS5waXNob3cudHYvbGl2ZS8xMDEzL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'shemaroo-tv',
    name: 'SHEMAROO TV',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/9042/400/400',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/9041/600/400',
    thumbnailImageHint: 'bollywood show',
    streamUrl: 'aHR0cHM6Ly9jZG4tMy5waXNob3cudHYvbGl2ZS8yMzAvbWFzdGVyLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'india-tv',
    name: 'INDIA TV',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/9062/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/9061/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'aHR0cHM6Ly9wbC1pbmRpYXR2bmV3cy5ha2FtYWl6ZWQubmV0L291dC92MS9kYjc5MTc5YjYwODY0MWNlYWE1YTRkMGRkMGZjYThkYS9pbmRleC5tM3U4',
    type: 'hls',
  },
  {
    id: 'aastha',
    name: 'AASTHA',
    category: 'Devotional',
    logoUrl: 'https://picsum.photos/seed/9072/400/400',
    logoImageHint: 'spiritual logo',
    thumbnailUrl: 'https://picsum.photos/seed/9071/600/400',
    thumbnailImageHint: 'devotional music',
    streamUrl: 'aHR0cHM6Ly9hYXN0aGFvdHQuYWthbWFpemVkLm5ldC8xMTA5MjMvc21pbDphYXN0aGF0di5zbWlsL2NodW5rbGlzdF9iMjYyODAwMC5tM3U4',
    type: 'hls',
  },
  {
    id: 'abp-news',
    name: 'ABP NEWS',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/9082/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/9081/600/400',
    thumbnailImageHint: 'breaking news',
    streamUrl: 'aHR0cHM6Ly9kMmw0YXI2eTNtcnM0ay5jbG91ZGZyb250Lm5ldC9saXZlLXN0cmVhbWluZy9hYnBuZXdzLWxpdmV0di9tYXN0ZXIubTN1OA==',
    type: 'hls',
  },
  {
    id: 'ndtv-india',
    name: 'NDTV INDIA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/9092/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/9091/600/400',
    thumbnailImageHint: 'news report',
    streamUrl: 'aHR0cHM6Ly9uZHR2aW5kaWFlbGVtYXJjaGFuYS5ha2FtYWl6ZWQubmV0L2hscy9saXZlLzIwMDM2NzkvbmR0dmluZGlhL21hc3Rlci5tM3U4',
    type: 'hls',
  },
  {
    id: 'times-now-navbharat',
    name: 'TIMES NOW NABBHARAT',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/9102/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/9101/600/400',
    thumbnailImageHint: 'news debate',
    streamUrl: 'aHR0cHM6Ly93d3cueW91dHViZS5jb20vZW1iZWQvNzdxTWFVdFYwMzA=',
    type: 'iframe',
  },
  {
    id: 'tv9-bharatvarsh',
    name: 'TV9 BHARATVARSH',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/9112/400/400',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/9111/600/400',
    thumbnailImageHint: 'news update',
    streamUrl: 'aHR0cHM6Ly9keWpteWl2M2JwMmV6LmNsb3VkZnJvbnQubmV0L3B1Yi1pb3R2OWhpbmp6Z3RwZS9saXZlYWJyL3BsYXlsaXN0Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'bollywood-movies',
    name: 'Bollywood Movies',
    category: 'Movies',
    logoUrl: 'https://picsum.photos/seed/9132/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/9131/600/400',
    thumbnailImageHint: 'bollywood poster',
    streamUrl: 'aHR0cHM6Ly9saXZlMjAuYm96enR2LmNvbS9naWF0dnBsYXlvdXQ3L2dpYXR2LTIwOTYxMi90cmFja3MtdjFhMS9tb25vLnRzLm0zdTg=',
    type: 'hls',
  },
  {
    id: 'dd-bharati',
    name: 'DD BHARATI',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/9142/400/400',
    logoImageHint: 'tv logo',
    thumbnailUrl: 'https://picsum.photos/seed/9141/600/400',
    thumbnailImageHint: 'indian culture',
    streamUrl: 'aHR0cHM6Ly9jZG4tMS5waXNob3cudHYvbGl2ZS8xMC9tYXN0ZXIubTN1OA==',
    type: 'hls',
  },
  {
    id: 'dd-tripura',
    name: 'DD TRIPURA',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/9152/400/400',
    logoImageHint: 'tv logo',
    thumbnailUrl: 'https://picsum.photos/seed/9151/600/400',
    thumbnailImageHint: 'regional show',
    streamUrl: 'aHR0cHM6Ly9kM3FzM2QycmtoZnFydC5jbG91ZGZyb250Lm5ldC9vdXQvdjEvNTJiOTk4ZTk1MTBkNDFjMjlhZDJjZWNhOGVhM2Q4NDkvaW5kZXhfMy5tM3U4',
    type: 'hls',
  },
  {
    id: 'the-movie-club-2',
    name: 'The Movie Club 2',
    category: 'English Movies',
    logoUrl: 'https://picsum.photos/seed/the-movie-club-2-logo/400/400',
    logoImageHint: 'movie logo',
    thumbnailUrl: 'https://picsum.photos/seed/the-movie-club-2-thumb/600/400',
    thumbnailImageHint: 'movie scene',
    streamUrl: 'aHR0cHM6Ly9jYy1lanJsNGF6Nzdndmw0LmFrYW1haXplZC5uZXQvdjEvbWFzdGVyLzM3MjJjNjBhODE1YzE5OWQ5YzBlZjM2YzViNzNkYTY4YTYyYjA5ZDEvY2MtZWpybDRhejdiZ3ZsNC9PVE0vT1RNX0tJTkdTX09GX0NPTUVEWV9TQU1TVU5HL3BsYXlsaXN0Lm0zdTg=',
    type: 'hls',
  },
  {
    id: 'divvya',
    name: 'DIVVYA',
    category: 'Devotional',
    logoUrl: 'https://picsum.photos/seed/divvya-logo/400/400',
    logoImageHint: 'spiritual logo',
    thumbnailUrl: 'https://picsum.photos/seed/divvya-thumb/600/400',
    thumbnailImageHint: 'devotional content',
    streamUrl: 'aHR0cHM6Ly92Zy1waXRhYXJhdHZsaXZlLmFrYW1haXplZC5uZXQvdjEvdmdsaXZlLXNrLTkwNjQ4Mi9wbGF5bGlzdC5tM3U4',
    type: 'hls',
  },
];

export const categories: { name: ChannelCategory; slug: string; imageUrl: string; imageHint: string; }[] = [
  { name: 'News', slug: 'news', imageUrl: 'https://picsum.photos/seed/cat-news/400/400', imageHint: 'news broadcast' },
  { name: 'Kids', slug: 'kids', imageUrl: 'https://picsum.photos/seed/new-cartoon/400/400', imageHint: 'cartoon characters' },
  { name: 'Entertainment', slug: 'entertainment', imageUrl: 'https://picsum.photos/seed/cat-ent/400/400', imageHint: 'movie set' },
  { name: 'Movies', slug: 'movies', imageUrl: 'https://picsum.photos/seed/cat-movies/400/400', imageHint: 'film reel' },
  { name: 'English Movies', slug: 'english-movies', imageUrl: 'https://picsum.photos/seed/cat-english-movies/400/400', imageHint: 'hollywood sign' },
  { name: 'Music', slug: 'music', imageUrl: 'https://picsum.photos/seed/cat-music/400/400', imageHint: 'live concert' },
  { name: 'Sports', slug: 'sports', imageUrl: 'https://picsum.photos/seed/cat-sports/400/400', imageHint: 'stadium lights' },
  { name: 'Infotainment', slug: 'infotainment', imageUrl: 'https://picsum.photos/seed/cat-info/400/400', imageHint: 'nature documentary' },
  { name: 'Devotional', slug: 'devotional', imageUrl: 'https://picsum.photos/seed/cat-devotional/400/400', imageHint: 'spiritual temple' },
  { name: 'Educational', slug: 'educational', imageUrl: 'https://picsum.photos/seed/cat-educational/400/400', imageHint: 'books library' },
  { name: 'Lifestyle', slug: 'lifestyle', imageUrl: 'https://picsum.photos/seed/cat-lifestyle/400/400', imageHint: 'healthy living' },
];

export function getChannels(category?: string): Channel[] {
  if (category) {
    return channels.filter(channel => channel.category.toLowerCase() === category.toLowerCase());
  }
  return channels;
}

export function getChannelById(id: string): Channel | undefined {
  return channels.find(channel => channel.id === id);
}

export function getChannelCategory(slug: string): { name: ChannelCategory; slug: string; imageUrl: string; imageHint: string; } | undefined {
    return categories.find(cat => cat.slug === slug);
}
