import type { Channel, ChannelCategory } from '@/lib/types';

export const channels: Channel[] = [
  {
    id: 'cbs-news',
    name: 'CBS News',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/102/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/101/600/400',
    thumbnailImageHint: 'news broadcast',
    streamUrl: 'https://cbsn-us.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8',
    type: 'hls',
  },
  {
    id: 'nick-bangla',
    name: 'NICK BANGLA',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/202/100/100',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/201/600/400',
    thumbnailImageHint: 'cartoon animation',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_1341.m3u8',
    type: 'hls',
  },
  {
    id: 'sony',
    name: 'SONY',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/302/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/301/600/400',
    thumbnailImageHint: 'red carpet',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_551.m3u8',
    type: 'hls',
  },
  {
    id: 'cartoon-network',
    name: 'Cartoon Network',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/402/100/100',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/401/600/400',
    thumbnailImageHint: 'cartoon characters',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_816.m3u8',
    type: 'hls',
  },
  {
    id: 'zb-cartoon',
    name: 'ZB Cartoon',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/502/100/100',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/501/600/400',
    thumbnailImageHint: 'cartoon fun',
    streamUrl: 'https://server.zillarbarta.com/zbcatun/video.m3u8',
    type: 'hls',
  },
  {
    id: 'discovery-bengali',
    name: 'DISCOVERY CHANNEL BENGALI',
    category: 'Infotainment',
    logoUrl: 'https://picsum.photos/seed/602/100/100',
    logoImageHint: 'discovery logo',
    thumbnailUrl: 'https://picsum.photos/seed/601/600/400',
    thumbnailImageHint: 'nature documentary',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_573.m3u8',
    type: 'hls',
  },
  {
    id: 'colors-bengali-hd',
    name: 'COLORS BENGALI HD',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/702/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/701/600/400',
    thumbnailImageHint: 'drama series',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_756.m3u8',
    type: 'hls',
  },
  {
    id: 'sonic-bangla',
    name: 'SONIC BANGLA',
    category: 'Kids',
    logoUrl: 'https://picsum.photos/seed/802/100/100',
    logoImageHint: 'kids logo',
    thumbnailUrl: 'https://picsum.photos/seed/801/600/400',
    thumbnailImageHint: 'action cartoon',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_1345.m3u8',
    type: 'hls',
  },
  {
    id: 'tv9-bangla',
    name: 'TV9 BANGLA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/902/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/901/600/400',
    thumbnailImageHint: 'news report',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_1735.m3u8',
    type: 'hls',
  },
  {
    id: 'r-bangla',
    name: 'R BANGLA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/1002/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/1001/600/400',
    thumbnailImageHint: 'breaking news',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_2780.m3u8',
    type: 'hls',
  },
  {
    id: 'rupashi-bangla',
    name: 'RUPASHI BANGLA',
    category: 'Entertainment',
    logoUrl: 'https://picsum.photos/seed/1102/100/100',
    logoImageHint: 'entertainment logo',
    thumbnailUrl: 'https://picsum.photos/seed/1101/600/400',
    thumbnailImageHint: 'drama series',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_3005.m3u8',
    type: 'hls',
  },
  {
    id: 'abp-ananda',
    name: 'ABP ANANDA',
    category: 'News',
    logoUrl: 'https://picsum.photos/seed/1202/100/100',
    logoImageHint: 'news logo',
    thumbnailUrl: 'https://picsum.photos/seed/1201/600/400',
    thumbnailImageHint: 'live news',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_672.m3u8',
    type: 'hls',
  },
  {
    id: 'sangeet-bangla',
    name: 'SANGEET BANGLA',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1302/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1301/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'https://mini.allinonereborn.fun/jiotv-inn/app/ts_live_740.m3u8',
    type: 'hls',
  },
  {
    id: 'b4u-music',
    name: 'B4U Music',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1402/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1401/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'https://cdnb4u.wiseplayout.com/B4U_Music/master.m3u8',
    type: 'hls',
  },
  {
    id: '9xm',
    name: '9XM',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1502/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1501/600/400',
    thumbnailImageHint: 'music video',
    streamUrl: 'https://9xjio.wiseplayout.com/9XM/master.m3u8',
    type: 'hls',
  },
  {
    id: '9x-jalwa',
    name: '9X Jalwa',
    category: 'Music',
    logoUrl: 'https://picsum.photos/seed/1602/100/100',
    logoImageHint: 'music logo',
    thumbnailUrl: 'https://picsum.photos/seed/1601/600/400',
    thumbnailImageHint: 'bollywood music',
    streamUrl: 'https://9xjio.wiseplayout.com/9XJALWA/master.m3u8',
    type: 'hls',
  },
];

export const categories: { name: ChannelCategory; slug: string }[] = [
  { name: 'News', slug: 'news' },
  { name: 'Kids', slug: 'kids' },
  { name: 'Entertainment', slug: 'entertainment' },
  { name: 'Music', slug: 'music' },
  { name: 'Infotainment', slug: 'infotainment' },
];

export function getChannels(category?: string): Channel[] {
  if (category) {
    return channels.filter(channel => channel.category.toLowerCase() === category);
  }
  return channels;
}

export function getChannelById(id: string): Channel | undefined {
  return channels.find(channel => channel.id === id);
}

export function getChannelCategory(slug: string): { name: ChannelCategory; slug: string } | undefined {
    return categories.find(cat => cat.slug === slug);
}
